apiVersion: v1
kind: Service
metadata:
  name: gameserver-service
  labels:
    app: gameserver-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3000
  selector:
    app: gameserver-service