### Get Game Stuffs
GET http://localhost:3000/api/game/mylovelykey



### Create Server
# @name CreateServer
POST http://localhost:3000/api/game/mylovelykey
Content-Type: application/json

{
    "name": "My Lovely Server",
    "current_players": 0,
    "max_players": 10,
    "ip": "127.0.0.1",
    "port": "25565"
}



### Update Server
POST http://localhost:3000/api/game/mylovelykey/{{CreateServer.response.body.id}}
Content-Type: application/json

{
    "name": "My Lovely Server",
    "current_players": 5,
    "max_players": 10,
    "ip": "127.0.0.1",
    "port": "25565",
    "password": "{{CreateServer.response.body.password}}"
}



### Test Server
POST https://gameservers.nick-hope.co.uk/api/game/KjyUfbGuOsTSq2cbP05M7hiwnwkgtLqzsjanzNN5cnbJfn7uGrOQ7DeaLqWo?page=1
Content-Type: application/json

{
    "name": "My Lovely Server",
    "current_players": 0,
    "max_players": 10,
    "ip": "127.0.0.1",
    "port": "25565"
}