apiVersion: v1
kind: Service
metadata:
  name: gameserver-service
  namespace: gameserver-service
  labels:
    app: gameserver-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: gameserver-service
